#!/usr/bin/env python3
"""Regression tests for deterministic generated lockfile comments."""

import importlib.util
import tempfile
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SPEC = importlib.util.spec_from_file_location(
    "normalize_lockfile", ROOT / "scripts" / "normalize-lockfile.py"
)
assert SPEC and SPEC.loader
NORMALIZER = importlib.util.module_from_spec(SPEC)
SPEC.loader.exec_module(NORMALIZER)


def render_lockfile(output_path, input_path):
    return (
        "# This file was autogenerated by uv via the following command:\n"
        f"#    uv pip compile --output-file {output_path} {input_path}\n"
        "example==1.0.0\n"
        f"    # via -r {input_path}\n"
    )


def main():
    stable_input = "/tmp/vllm-gb10-build.in"
    stable_output = "locks/python-build.txt"
    with tempfile.TemporaryDirectory() as directory:
        outputs = []
        for suffix in ("a1B2c", "x9Y8z"):
            random_input = f"/tmp/vllm-gb10-build-{suffix}.in"
            random_output = (
                f"/runner/_temp/vllm-gb10-generator-{suffix}/"
                "locks/python-build.txt"
            )
            lockfile = Path(directory) / f"lock-{suffix}.txt"
            lockfile.write_text(render_lockfile(random_output, random_input))
            NORMALIZER.normalize_lockfile(
                lockfile, random_input, stable_input
            )
            NORMALIZER.normalize_lockfile(
                lockfile, random_output, stable_output
            )
            normalized = lockfile.read_text()
            assert random_input not in normalized
            assert random_output not in normalized
            assert normalized.count(stable_input) == 2
            assert normalized.count(stable_output) == 1
            outputs.append(normalized)
        assert outputs[0] == outputs[1]
    print("All lockfile normalization tests passed!")


if __name__ == "__main__":
    main()
