#!/usr/bin/env python3
"""Regression tests for deterministic generated lockfile comments."""

import importlib.util
import tempfile
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SPEC = importlib.util.spec_from_file_location(
    "normalize_lockfile", ROOT / "scripts" / "normalize-lockfile.py"
)
assert SPEC and SPEC.loader
NORMALIZER = importlib.util.module_from_spec(SPEC)
SPEC.loader.exec_module(NORMALIZER)


def render_lockfile(input_path):
    return (
        "# This file was autogenerated by uv via the following command:\n"
        f"#    uv pip compile --output-file locks/python-build.txt {input_path}\n"
        "example==1.0.0\n"
        f"    # via -r {input_path}\n"
    )


def main():
    stable_path = "/tmp/vllm-gb10-build.in"
    with tempfile.TemporaryDirectory() as directory:
        outputs = []
        for suffix in ("a1B2c", "x9Y8z"):
            random_path = f"/tmp/vllm-gb10-build-{suffix}.in"
            lockfile = Path(directory) / f"lock-{suffix}.txt"
            lockfile.write_text(render_lockfile(random_path))
            NORMALIZER.normalize_lockfile(lockfile, random_path, stable_path)
            normalized = lockfile.read_text()
            assert random_path not in normalized
            assert normalized.count(stable_path) == 2
            outputs.append(normalized)
        assert outputs[0] == outputs[1]
    print("All lockfile normalization tests passed!")


if __name__ == "__main__":
    main()
