#!/usr/bin/env bash
# scripts/render-metadata.sh
#
# Reads versions.env, lockfile SHA256s, and git rev-parse HEAD,
# then emits build-metadata.yaml to stdout.
#
# Usage:
#   export SOURCE_DATE_EPOCH=$(git log -1 --format=%ct)
#   scripts/render-metadata.sh > build-metadata.yaml
#
# build-metadata.yaml is in .gitignore - it is generated at build time and
# COPY-ed into the image by the Dockerfile. It must exist in the build context
# before running docker buildx build.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

# Load versions.env
set -a
# shellcheck source=../versions.env
source "${REPO_ROOT}/versions.env"
set +a

# Git SHA of this repo
REPO_COMMIT="$(git -C "${REPO_ROOT}" rev-parse HEAD)"

# Build timestamp from SOURCE_DATE_EPOCH (set by caller, not stored in repo)
if [[ -z "${SOURCE_DATE_EPOCH:-}" ]]; then
  echo "ERROR: SOURCE_DATE_EPOCH must be set before calling render-metadata.sh" >&2
  echo "  Set it with: export SOURCE_DATE_EPOCH=\$(git log -1 --format=%ct)" >&2
  exit 1
fi
# date -d is GNU (Linux); date -r is BSD (macOS). Try both.
BUILD_TIMESTAMP="$(date -u -d "@${SOURCE_DATE_EPOCH}" '+%Y-%m-%dT%H:%M:%SZ' 2>/dev/null \
  || date -u -r "${SOURCE_DATE_EPOCH}" '+%Y-%m-%dT%H:%M:%SZ')"

# Lockfile SHA256s
sha256_of() {
  sha256sum "$1" | awk '{print $1}'
}

LOCK_BOOTSTRAP_SHA256="$(sha256_of "${REPO_ROOT}/locks/python-bootstrap.txt")"
LOCK_BUILD_SHA256="$(sha256_of "${REPO_ROOT}/locks/python-build.txt")"
LOCK_RUNTIME_SHA256="$(sha256_of "${REPO_ROOT}/locks/python-runtime.txt")"
LOCK_APT_PACKAGES_SHA256="$(sha256_of "${REPO_ROOT}/locks/apt-packages.txt")"
LOCK_APT_SOURCES_SHA256="$(sha256_of "${REPO_ROOT}/locks/apt-sources.list")"

cat <<'YAML_EOF'
# build-metadata.yaml - generated by scripts/render-metadata.sh
# DO NOT EDIT - regenerate with: scripts/render-metadata.sh > build-metadata.yaml
YAML_EOF

cat <<YAML_EOF
---
build_timestamp: "${BUILD_TIMESTAMP}"
repo_commit: "${REPO_COMMIT}"

base:
  image: "${CUDA_BASE_IMAGE}"
  digest: "${CUDA_BASE_DIGEST}"

gb10_build: ${GB10_BUILD}

pytorch:
  torch: "${TORCH_VERSION}"
  torchvision: "${TORCHVISION_VERSION}"
  torchaudio: "${TORCHAUDIO_VERSION}"
  triton: "${TRITON_VERSION}"
  index_url: "${PYTORCH_INDEX_URL}"

uv:
  version: "${UV_VERSION}"

nccl:
  repo: "${NCCL_REPO}"
  ref: "${NCCL_REF}"
  commit: "${NCCL_COMMIT}"

vllm:
  repo: "${VLLM_REPO}"
  ref: "${VLLM_REF}"
  commit: "${VLLM_COMMIT}"

flashinfer:
  repo: "${FLASHINFER_REPO}"
  ref: "${FLASHINFER_REF}"
  commit: "${FLASHINFER_COMMIT}"
  cuda_arch_list: "${FLASHINFER_CUDA_ARCH_LIST}"

cuda_companions:
  nvshmem: "${NVSHMEM_VERSION}"
  tvm_ffi: "${TVM_FFI_VERSION}"
  tilelang: "${TILELANG_VERSION}"
  numba: "${NUMBA_VERSION}"

runtime_seeds:
  ray: "${RAY_VERSION}"
  fastsafetensors: "${FASTSAFETENSORS_VERSION}"
  instanttensor: "${INSTANTTENSOR_VERSION}"

arch:
  torch_cuda_arch_list: "${TORCH_CUDA_ARCH_LIST}"
  flashinfer_cuda_arch_list: "${FLASHINFER_CUDA_ARCH_LIST}"

lockfiles:
  python_bootstrap:
    file: "locks/python-bootstrap.txt"
    sha256: "${LOCK_BOOTSTRAP_SHA256}"
  python_build:
    file: "locks/python-build.txt"
    sha256: "${LOCK_BUILD_SHA256}"
  python_runtime:
    file: "locks/python-runtime.txt"
    sha256: "${LOCK_RUNTIME_SHA256}"
  apt_packages:
    file: "locks/apt-packages.txt"
    sha256: "${LOCK_APT_PACKAGES_SHA256}"
  apt_sources:
    file: "locks/apt-sources.list"
    sha256: "${LOCK_APT_SOURCES_SHA256}"
YAML_EOF
